### PR TITLE
Configuring test environment and testing crumble service

### PR DESCRIPTION
**Pull request by italopaiva**
* Test environment with karma, jasmine and coverage was configured;
* The _crumble_ service was tested.

### CODE REVIEW

**Comment by raphinesse** [comment]
Thanks for contributing!
I will review your PR next week.

**Review by raphinesse — CHANGES_REQUESTED** [review]
(deleted)

**Review by raphinesse — DISMISSED** [review]
(deleted)

**Comment by raphinesse** [comment]
All right, I got a bit carried away with optimizing the tests :sweat_smile:. I changed quite some things, but the aspects being tested haven't changed much. I tried hard to make the individual commits as isolated as possible, so please do tell me what you think of the changes. Also feel free to push further commits if you spot any errors. For my part this is good to go. :ship:

Thanks again for this PR. Adding tests is something that had been on my TODO list for a long time. Your contribution layed great groundwork for that! :sparkles:

One last question: How would you like your name to be listed as a contributor? Just with your username or with your full name too?

**Comment by italopaiva** [comment]
These tests really needed some improvements indeed, because I've made them in a hurry to use your component in a project. Glad you improved them! 
I'll try to see the results of your modifications as soon as possible.

For the contributors section you can use "Italo Paiva" as my name and my github username too (@italopaiva).

Thanks!

**Comment by italopaiva** [comment]
@raphinesse, sorry for the long wait! I could finally manage some time to check this out. The tests are good to go for me too, nice improvements!

**Pull request merged**
